use_frameworks!

platform :ios, '8.0'

target 'PSSearch_Example' do
	pod 'PSSearch', :path => '/Users/rsf/Documents/Project/PSSearch/PSSearch.podspec'

  target 'PSSearch_Tests' do
    inherit! :search_paths

    
  end
end

